import numpy as np
import matplotlib.pyplot as plt
import os
from matplotlib.lines import Line2D
from matplotlib.legend_handler import HandlerBase


# 自定义图例处理器：显示多个圆点
class MultiDotHandler(HandlerBase):
    def __init__(self, num_dots=3, **kwargs):
        super().__init__(**kwargs)
        self.num_dots = num_dots  # 圆点数量，可通过参数控制

    def create_artists(self, legend, orig_handle,
                       xdescent, ydescent, width, height, fontsize, trans):
        # 创建指定数量的圆点，横向排列
        dots = []
        for i in range(self.num_dots):
            # 计算每个圆点的位置，均匀分布
            x = xdescent + (i + 1) * width / (self.num_dots + 1)
            y = ydescent + height / 2  # 垂直居中

            # 创建圆点
            dot = Line2D(
                [x], [y],
                marker='o',
                markersize=orig_handle.get_markersize(),
                markerfacecolor=orig_handle.get_markerfacecolor(),
                markeredgecolor='none',
                linestyle='',
                transform=trans
            )
            dots.append(dot)
        return dots


def plot_avg_smoothed_displacement(
        csv_file: str,
        output_path: str,
        plot_x_min: float = -20,
        plot_x_max: float = 20,
        disp_labels: tuple[str, str, str] = ("$x$", "$y$", "$z$"),
        y_legend_dot_count: int = 3  # 新增参数：控制y图例的圆点数量
):
    """Read the CSV generated by the smoothing script and reproduce the publication‑quality figure."""

    # ─── 1. Load data ───────────────────────────────────────────────────────────
    data = np.loadtxt(csv_file, delimiter=",", skiprows=1)
    rel_x = data[:, 0]
    disp_x2, disp_y2, disp_z2 = data[:, 3], data[:, 2], data[:, 1]

    # ─── 2. Restrict x‑range for plotting ──────────────────────────────────────
    mask = (rel_x >= plot_x_min) & (rel_x <= plot_x_max)
    rel_x_plot = rel_x[mask]

    # ─── 3. Create figure ───────────────────────────────────────────────────────
    fig = plt.figure(figsize=(8, 5))
    ax = plt.gca()
    fs = 23  # consistent font size

    # 绘制各方向位移，保存线条对象用于图例
    x_line, = ax.plot(rel_x_plot, disp_x2[mask], color="red", linestyle="-", linewidth=2.2, label=disp_labels[0])
    y_line, = ax.plot(rel_x_plot, disp_y2[mask], color="C2", linestyle="", marker="o",
                      markersize=4, markevery=5, label=disp_labels[1])
    z_line, = ax.plot(rel_x_plot, disp_z2[mask], color="C0", linestyle="dashed", linewidth=2.2, label=disp_labels[2])

    # 设置坐标轴
    ax.set_xlabel("z (Å)", fontsize=fs)
    ax.set_ylim(bottom=0)
    ax.set_ylabel("$D$ (m$^2$/s × 1e-8)", fontsize=fs + 2)
    plt.xticks(fontsize=fs)
    plt.yticks(fontsize=fs)
    ax.set_xlim(plot_x_min, plot_x_max)
    ax.grid(False)

    # ─── 自定义图例设置 ───────────────────────────────────────
    # 创建图例元素
    handles = [
        x_line,  # x保持默认图例样式
        Line2D([], [], color="none", marker="o", markersize=8,
               markerfacecolor="C2", markeredgecolor="none", label=disp_labels[1]),  # y使用自定义样式
        z_line  # z保持默认图例样式
    ]

    # 创建处理器映射，只对y方向的图例应用多圆点处理
    # 通过创建一个唯一标识的空对象来专门映射y图例
    y_legend_identifier = Line2D([], [])
    handler_map = {y_legend_identifier: MultiDotHandler(num_dots=y_legend_dot_count)}

    # 将y方向的图例与自定义处理器关联
    handles[1] = y_legend_identifier
    handles[1].set_markerfacecolor("C2")
    handles[1].set_markersize(6)
    handles[1].set_label(disp_labels[1])

    # 生成图例
    ax.legend(
        handles=handles,
        fontsize=fs+2 ,
        frameon=False,
        handler_map=handler_map
    )

    plt.tight_layout()

    # ─── 4. Save ───────────────────────────────────────────────────────────────
    os.makedirs(output_path, exist_ok=True)
    outfile = os.path.join(output_path, "difffusion.png")
    plt.savefig(outfile, dpi=400, bbox_inches="tight", pad_inches=0.02)
    plt.close()
    print(f"✅ 图像已保存：{outfile}")


if __name__ == "__main__":
    # ✂──────────────────────────── EDIT HERE ────────────────────────────✂ #
    csv_file = r"E:\free_energy\0_all_newpot-2\100\msd\avg_smoothed_displacement_xyz2_relative_to_interface.csv"
    output_path = r"E:\free_energy\0_all_newpot-2\100\msd\plot"

    # 可以通过此参数控制y图例的圆点数量，默认3个
    plot_avg_smoothed_displacement(csv_file, output_path, y_legend_dot_count=4)
